let PREFIX = "AUTH"

export const LOGIN_ACTION  = `${PREFIX} LOGIN_ACTION`;
export const LOGIN_ACTION_OK  = `${PREFIX} LOGIN_ACTION_OK`;

export const REGISTRATION_ACTION  = `${PREFIX} REGISTRATION_ACTION`;
export const REGISTRATION_ACTION_OK  = `${PREFIX} REGISTRATION_ACTION_OK`;

export const LOGOUT_ACTION  = `${PREFIX} LOGOUT_ACTION`;
export const LOGOUT_ACTION_OK  = `${PREFIX} LOGOUT_ACTION_OK`;