let PREFIX = "AUTH"
export const OPEN_AUTH_ACTION  = `${PREFIX} OPEN_AUTH_ACTION`;


export const LOGIN_ACTION  = `${PREFIX} LOGIN_ACTION`;
export const LOGIN_ACTION_OK  = `${PREFIX} LOGIN_ACTION_OK`;

export const REGISTRATION_ACTION  = `${PREFIX} REGISTRATION_ACTION`;
export const REGISTRATION_ACTION_OK  = `${PREFIX} REGISTRATION_ACTION_OK`;